SET (GIT_HASH "unknown")
FIND_PACKAGE (Git QUIET)
IF (GIT_FOUND)
  EXECUTE_PROCESS (
    COMMAND git rev-parse --short HEAD
    RESULT_VARIABLE SHORT_HASH_RESULT
    OUTPUT_VARIABLE GIT_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
ENDIF ()
CONFIGURE_FILE (${CMAKE_CURRENT_SOURCE_DIR}/version.hpp.in
                ${CMAKE_CURRENT_BINARY_DIR}/version.hpp)
