name: Native Ubuntu 22.04 pipeline

on: [push]

jobs:
  documentation_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: Install development dependencies
        run: ./.devcontainer/setup_documentation_environment_on_ubuntu_22.sh
      - name: Configure 
        run: ./scripts/configure.sh
      - name: Make documentation
        run: ./scripts/document.sh
      
