name: Native Ubuntu 22.04 pipeline

on: [push]

jobs:
  build_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: Install development dependencies
        run: ./.devcontainer/setup_build_environment_on_ubuntu_22.sh
      - name: Check formating
        run: make format
      - name: Configure
        run: make configure_release
      - name: Build
        run: make build_release
      - name: Tests
        run: make test
      - name: Validation
        run: make validate
      - name: Packaging
        run: make packaging
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ./build-x86-Release/stm32-helloworld-0.0.1-Linux.deb

  Test-debian-package-installation-on-ubuntu-22-04:
    needs: build_pipeline
    runs-on: ubuntu-22.04
    steps:
    - name: Download package
      uses: actions/download-artifact@v2
      with:
        name: package

    - name: Install package
      run: sudo apt install -y stm32-helloworld-0.0.1-Linux.deb

    - name: Smoke test desktop_client
      run: desktop_client
