name: Native Ubuntu 22.04 pipeline

on: [push]

jobs:
  build_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: Install development dependencies
        run: ./.devcontainer/setup_build_environment_on_ubuntu_22.sh
      - name: Check formating
        run: make format
      - name: Configure
        run: make configure_release
      - name: Build
        run: make build_release
      - name: Tests
        run: make test
      - name: Validation
        run: make validate
      - name: Packaging
        run: make packaging
